### ISSUE TITLE
recognise faces from live cc camera stream(with ip known)

### ISSUE THREAD

**Issue by VellalaVineethKumar** [lazyoracle/video-face-detection#1]
* Python version:3.7.1(anaconda distrubution)
* Operating System:ubuntu 16.04

### Description
1) i have the IP of cc camera eg.10.2.0.10
2) I have the pictures of my friend's face (known peoples folder)
3) I want to recognize his face from the stream I get from cc camera(just like a webcam)
what changes can i make to this to happen?
please help!

**Comment by lazyoracle** [comment]
I am unable to comment on it without full knowledge of the transmission protocols used by your particular model of CC camera. The basic idea however is to make use one of the libraries that allow for RTSP or other streaming protocol parsing and use that as an input to CV2 video feed. You might want to take a look at the following - 
https://github.com/ekwoodrich/python-netsurv

**Comment by VellalaVineethKumar** [comment]
@lazyoracle 
my cc camera uses RTSP for live video streaming

**Comment by lazyoracle** [comment]
I haven't worked with `rtsp` much but try googling `rtsp opencv python` and you should find something. I made the following quick hack. 
First add the following to the import statements
`import os`

Then inside `videoFaceDet()`, make the following changes for the `video` variable to now point to `VideoCapture` from `rtsp` feed.  Remember to update the IP address inside the `rtsp` URL. 


```
os.environ["OPENCV_FFMPEG_CAPTURE_OPTIONS"] = "rtsp_transport;udp"`
ip_camera = "192.168.1.2" #Provide camera IP
port_camera = "8888" #Provide port. Remove from URL below if unknown
video = cv2.VideoCapture("rtsp://"+ip_camera+":"+port+"/camera", cv2.CAP_FFMPEG)

```
